const CONST = {
  GAME_WIDTH: 990,
  GAME_HEIGHT: 820,
  GAME_BACKGROUND: 0xffffff,
  START_X: 42,
  START_Y: 225,
  CUBE_WIDTH: 67,
  CUBE_HEIGHT: 60,
  FRAMES: ['CUBE_CHETRA', 'CUBE_DOZER', 'CUBE_FPK', 'CUBE_MKSM', 'CUBE_PK'],
  SCORE: 0,
  GOAL: 5,
  MOVES: 10,
  LEVEL: 1,
  HIGHSCORE: 0,
  INLINE_LIMIT: 9,
  FONT_PROPS: {
    FAMILY: 'Calibri',
    SIZE_XL: 100,
    SIZE_L: 48,
    SIZE_M: 32,
    SIZE_S: 24,
    FC_YELLOW: '#F3B411',
    FC_PURPLE: '#610C57',
    FC_WHITE: '#FFFFFF',
    FC_BLACK: '#000000',
  },
  TEXT: {
    BEGIN_TEXT: 'Нажмите, чтобы начать игру',
    NEW_RECORD: 'Отлично, Вы установили свой рекорд!',
    CHEERUP: 'Вы можете лучше, поднажмите!',
    NEW_SCORE: 'Ваш новый результат(очков):',
    BEST_SCORE: 'Ваш лучший результат(очков):',
    AGAIN: 'Попробуем еще раз?!',
  },
  P_BAR: {
    BAR_COLOR: 0xF3B411,
    BAR_WIDTH: 410,
    BAR_HEIGHT: 25,
  },
};

export default CONST;
