const CONST = {
  GAME_WIDTH: 990,
  GAME_HEIGHT: 820,
  GAME_BACKGROUND: 0xffffff,
  START_X: 45,
  START_Y: 230,
  CUBE_WIDTH: 60,
  CUBE_HEIGHT: 50,
  FRAMES: ['CUBE_CHETRA', 'CUBE_DOZER', 'CUBE_FPK', 'CUBE_MKSM', 'CUBE_PK'],
  SCORE: 0,
  GOAL: 5,
  MOVES: 10,
  LEVEL: 1,
  HIGHSCORE: 0,
  INLINE_LIMIT: 9,
  TEXT: {
    MAIN_TITLE: 'ЧЕТРикс',
    BEGIN_TEXT: 'Нажмите, чтобы начать игру',
    NEW_RECORD: 'Отлично, Вы установили свой рекорд!',
    CHEERUP: 'Вы можете лучше, поднажмите!',
    NEW_SCORE: 'Ваш новый результат(очков):',
    BEST_SCORE: 'Ваш лучший результат(очков):',
    AGAIN: 'Попробуем еще раз?!',
  },
  COLOR_YELLOW: '#F3B411',
  COLOR_PURPLE: '#610C57',
  COLOR_WHITE: '#ffffff',
  P_BAR: {
    COLOR_GREEN: '#ffffff',
    COLOR_NAVY: 0xffffff,
    BAR_WIDTH: 420,
    BAR_HEIGHT: 30,
  },
};

export default CONST;
